FROM registry.ci.openshift.org/openshift/release:golang-1.20
ENV GO111MODULE=on
ENV GOFLAGS=""

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.53.2
RUN yum install -y docker && \
    yum clean all

RUN go install golang.org/x/tools/cmd/goimports@v0.1.0 && \
    go install github.com/onsi/ginkgo/ginkgo@v1.16.1 && \
    go install go.uber.org/mock/mockgen@v0.4.0 && \
    go install gotest.tools/gotestsum@v1.6.3 && \
    go install github.com/axw/gocov/gocov@v1.1.0 && \
    go install github.com/AlekSi/gocov-xml@v1.1.0
