FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.21 AS builder

WORKDIR /go/src/github.com/openshift/assisted-installer
ENV GOFLAGS="-mod=vendor"

COPY . .
RUN make controller

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

LABEL io.openshift.release.operator=true

# Install minimal runtime dependencies and download openshift clients
RUN microdnf install -y tar gzip && microdnf clean all && \
    curl -L -s "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/latest/amd64/openshift-client-linux-amd64-rhel9.tar.gz" | tar xvz -C /usr/bin && \
    chmod +x /usr/bin/oc /usr/bin/kubectl

COPY --from=builder /go/src/github.com/openshift/assisted-installer/build/assisted-installer-controller /usr/bin/assisted-installer-controller

ENTRYPOINT ["/usr/bin/assisted-installer-controller"]
