FROM quay.io/centos/centos:centos8

RUN yum -y install make gcc unzip wget curl rsync && yum clean all && \
    curl -SsL https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.6.0/openshift-client-linux-4.6.0.tar.gz | tar -xz -C /usr/bin;
    
copy build/assisted-installer-controller /
ARG GIT_REVISION
LABEL "git_revision"=${GIT_REVISION}
ARG QUAY_TAG_EXPIRATION
LABEL "quay.expires-after"=${QUAY_TAG_EXPIRATION}
ENTRYPOINT ["/assisted-installer-controller"]
