FROM registry.ci.openshift.org/openshift/release:golang-1.15 AS builder
ENV GOFLAGS=-mod=mod
WORKDIR /go/src/github.com/openshift/assisted-installer

# Bring in the go dependencies before anything else so we can take
# advantage of caching these layers in future builds.
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .
RUN make controller-ocp

FROM quay.io/centos/centos:centos8

COPY --from=builder /go/src/github.com/openshift/assisted-installer/build/assisted-installer-controller-ocp /usr/bin/assisted-installer-controller-ocp

ENTRYPOINT ["/usr/bin/assisted-installer-controller-ocp"]
