FROM registry.access.redhat.com/ubi9/go-toolset:1.25 AS builder
ARG TARGETPLATFORM
ENV GOFLAGS=-mod=mod
WORKDIR /go/src/github.com/openshift/assisted-installer

# Workaround for creating build folder
USER root

# Bring in the go dependencies before anything else so we can take
# advantage of caching these layers in future builds.
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .
RUN git config --global --add safe.directory '*'; \
    TARGETPLATFORM=$TARGETPLATFORM make controller

# Extract the commit reference from which the image is built
RUN git rev-parse --short HEAD > /commit-reference.txt

# NOTE: UBI9 version 9.4 chosen for Konflux compatibility (Dec 2025)
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71
ARG TARGETPLATFORM

RUN microdnf install -y tar gzip rsync which procps-ng findutils && microdnf clean all

# openshift clients
ARG TARGETARCH
RUN case "${TARGETARCH}" in \
        "") ARCH=amd64 ;; \
        *) ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -L -s "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/latest/${ARCH}/openshift-client-linux-${ARCH}-rhel9.tar.gz" | tar xvz -C /usr/bin && \
    chmod +x /usr/bin/oc /usr/bin/kubectl

COPY --from=builder /go/src/github.com/openshift/assisted-installer/build/assisted-installer-controller /usr/bin/assisted-installer-controller

# Copy the commit reference from the builder
COPY --from=builder /commit-reference.txt /commit-reference.txt

ENTRYPOINT ["/usr/bin/assisted-installer-controller"]
