FROM registry.ci.openshift.org/openshift/release:golang-1.17
ENV GO111MODULE=on
ENV GOFLAGS=""

COPY --from=quay.io/app-sre/golangci-lint:v1.37.1 /usr/bin/golangci-lint /usr/bin/golangci-lint
RUN yum install -y docker && \
    yum clean all
RUN go install golang.org/x/tools/cmd/goimports@v0.0.0-20200520220537-cf2d1e09c845 \
    && go install github.com/onsi/ginkgo/ginkgo@v1.12.2 \
    && go install github.com/golang/mock/mockgen@v1.4.3 \
    && go install gotest.tools/gotestsum@v1.6.3 \
    && go install github.com/axw/gocov/gocov@latest \
    && go install github.com/AlekSi/gocov-xml@v0.0.0-20190121064608-3a14fb1c4737
