FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.24 AS builder
ARG TARGETOS
ARG TARGETARCH

ENV COMPONENT_NAME=installer
ENV COMPONENT_VERSION=1.0.0
ENV COMPONENT_TAG_EXTENSION=" "
ENV GOFLAGS="-p=4"
ENV GOEXPERIMENT=strictfipsruntime
ENV BUILD_TAGS="strictfipsruntime"

ENV USER_UID=1001 \
    USER_NAME=assisted-installer

COPY --chown=${USER_UID} . /app
WORKDIR /app

RUN CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -o installer src/main/main.go


# Package stage to provide nsenter (util-linux-core is pre-installed in UBI9)
FROM registry.access.redhat.com/ubi9/ubi:9.4 AS package-stage

# Metadata stage for Konflux version resolution compatibility
FROM registry.redhat.io/rhel9-4-els/rhel:9.4 AS rhel-metadata

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4
ARG release=main
ARG version=latest

COPY --from=package-stage /usr/bin/nsenter /usr/bin/nsenter

# Copy version metadata for Konflux machine-os version resolution
COPY --from=rhel-metadata /etc/redhat-release /etc/redhat-release
COPY --from=rhel-metadata /etc/system-release-cpe /etc/system-release-cpe
COPY --from=rhel-metadata /usr/lib/os-release /usr/lib/os-release

COPY LICENSE /licenses/
COPY --from=builder /app/installer /installer
COPY --from=builder /app/deploy/assisted-installer-controller /assisted-installer-controller/deploy

ENTRYPOINT ["/installer"]

LABEL com.redhat.component="multicluster-engine-assisted-installer-container" \
      name="multicluster-engine/assisted-installer-rhel9" \
      version="${version}" \
      upstream-ref="${version}" \
      upstream-url="https://github.com/openshift/assisted-installer" \
      url="https://github.com/openshift/assisted-installer" \
      summary="OpenShift Assisted Installer" \
      io.k8s.display-name="OpenShift Assisted Installer" \
      maintainer="Liat Gamliel <lgamliel@redhat.com>" \
      description="OpenShift Assisted Installer" \
      io.k8s.description="OpenShift Assisted Installer" \
      distribution-scope="public" \
      release="${release}" \
      vendor="Red Hat, Inc." \
      io.openshift.tags="OpenShift 4" \
      upstream_commit="${version}" \
      org.label-schema.vcs-ref="${version}" \
      org.label-schema.vcs-url="https://github.com/openshift/assisted-installer"
