FROM registry.access.redhat.com/ubi9/go-toolset:1.25 AS builder
ARG TARGETPLATFORM
ENV GOFLAGS=-mod=mod
WORKDIR /go/src/github.com/openshift/assisted-installer

# Workaround for creating build folder
USER root

# Bring in the go dependencies before anything else so we can take
# advantage of caching these layers in future builds.
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .
RUN git config --global --add safe.directory '*'; \
    TARGETPLATFORM=$TARGETPLATFORM make installer

# Extract the commit reference from which the image is built
RUN git rev-parse --short HEAD > /commit-reference.txt

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:17fd831ced9434de0a984d60b3fbe61008308261ba98bbc348d6fbdef05fa7c0

RUN microdnf install -y util-linux-core && microdnf clean all

COPY --from=builder /go/src/github.com/openshift/assisted-installer/build/installer /usr/bin/installer
COPY --from=builder /go/src/github.com/openshift/assisted-installer/deploy/assisted-installer-controller /assisted-installer-controller/deploy

# Copy the commit reference from the builder
COPY --from=builder /commit-reference.txt /commit-reference.txt

ENTRYPOINT ["/usr/bin/installer"]

