FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.25 AS builder
ARG TARGETOS
ARG TARGETARCH

ENV COMPONENT_NAME=assisted-installer-reporter
ENV COMPONENT_VERSION=1.0.0
ENV COMPONENT_TAG_EXTENSION=" "
ENV GOFLAGS="-p=4"

ENV USER_UID=1001 \
    USER_NAME=assisted-installer

COPY --chown=${USER_UID} . /app
WORKDIR /app
RUN CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o assisted-installer-controller src/main/assisted-installer-controller/assisted_installer_main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71
ARG release=main
ARG version=latest

# Install tools using rpm-prefetching (configured in rpm-prefetching/assisted-installer-controller/rpms.in.yaml)
RUN microdnf install -y openshift-clients tar gzip rsync which findutils procps-ng && microdnf clean all

COPY LICENSE /licenses/
COPY --from=builder /app/assisted-installer-controller /assisted-installer-controller

ENTRYPOINT ["/assisted-installer-controller"]

LABEL com.redhat.component="assisted-installer-controller" \
      name="rhai/assisted-installer-controller-rhel9" \
      version="${version}" \
      cpe="cpe:/a:redhat:assisted_installer:2.38::el9" \
      upstream-ref="${version}" \
      upstream-url="https://github.com/openshift/assisted-installer" \
      url="https://github.com/openshift/assisted-installer" \
      summary="OpenShift Assisted Installer Controller" \
      io.k8s.display-name="OpenShift Assisted Installer Controller" \
      maintainer="Liat Gamliel <lgamliel@redhat.com>" \
      description="OpenShift Assisted Installer Controller" \
      io.k8s.description="OpenShift Assisted Installer Controller" \
      distribution-scope="public" \
      release="${release}" \
      vendor="Red Hat, Inc." \
      io.openshift.tags="OpenShift 4" \
      upstream_commit="${version}" \
      org.label-schema.vcs-ref="${version}" \
      org.label-schema.vcs-url="https://github.com/openshift/assisted-installer"

